In [33]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [34]:
import numpy as np

In [35]:
l=[1 ,3, 9, 12, 18]
arr1= np.array(l)
arr1

array([ 1,  3,  9, 12, 18])

In [36]:
l=[[1,5,2,0],[3,4,7,6]]
arr2=np.array(l)
arr2

array([[1, 5, 2, 0],
       [3, 4, 7, 6]])

In [37]:
l=[['7','6'],['5','4'],['3','2']]
arr3 = np.array(l)
arr3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [38]:
l=[[11, 52 ,20, 50],[34 ,61 ,43 ,17]]
arr4= np.array(l)
arr4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

In [39]:

arr = np.add(arr1,arr1)
arr

array([ 2,  6, 18, 24, 36])

In [40]:
arr = arr1 * 10
arr

array([ 10,  30,  90, 120, 180])

In [ ]:
intarr1 = arr1.astype(np.int64)
intarr2 = arr2.astype(np.int64)
intarr3 = arr3.astype(np.int64)
intarr4 = arr4.astype(np.int64)
print('arr1', intarr1.dtype)
print('arr2', intarr2.dtype)
print('arr3', intarr3.dtype)
print('arr4', intarr4.dtype)


arr1 int64
arr2 int64
arr3 int64
arr4 int64


dtype('int64')

In [ ]:
a1 = np.zeros(3,5)
a2 = np.ones(2,8)
a3 = np.empty(6,3)
a1
a2
a3