# Lab 01

## Install numpy

In [ ]:
pip install numpy # to be used win shell

### open any pyhton coding environment

In [3]:
import numpy as np

## Creating ndarrays
### Example 1
Note:
- Default data type in most cases in float64

# Array creation functions
## 1. array
- Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype.
- Copies the input data by default.

In [ ]:
# create array using array function
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
# Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
arr2.ndim
arr2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [8]:
#Unless explicitly specified, np.array tries to infer a good data type for the array that it creates
# The data type is stored in a special dtype object
print( arr1.dtype)
print( arr2.dtype)

float64
int64


In [14]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
print(arr3)
print( arr3.dtype)

[1. 2. 3.]
float64


In [13]:
arr4 = np.array([1, 2, 3], dtype=np.int32)
print(arr4)
print(arr4.dtype)

[1 2 3]
int32


### To create a higher dimensional array with these methods, pass a tuple for the shape

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Note:
1. zeros_like takes another array and produces a ones array of the same shape and dtype.
2. Explore it at your own



In [17]:
np.empty((2, 3, 2))  # initial garbage values are displayed

array([[[5.06286193e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

## arange() (similar to range)
- arange is an array-valued version of the built-in Python range function, but returns an ndarray instead of a list.

- -ve or 0 paramter does not create an array



In [23]:
arr5= np.arange(15)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Some other Array creation functions
1. ones, ones_like
Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and
produces a ones array of the same shape and dtype.

2. empty, empty_like
Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

3.eye, identity
Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)



In [ ]:
arr6= np.