In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
l=[1 ,3, 9, 12, 18]
arr1= np.array(l)
arr1

array([ 1,  3,  9, 12, 18])

In [5]:
l=[[1,5,2,0],[3,6,4,7]]
arr2=np.array(l)
arr2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [6]:
l=[['7','6'],['5','4'],['3','2']]
arr3 = np.array(l)
arr3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [7]:
l=[[11, 52 ,20, 50],[34 ,61 ,43 ,17]]
arr4= np.array(l)
arr4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

In [8]:

arr = np.add(arr1,arr1)
arr

array([ 2,  6, 18, 24, 36])

In [9]:
arr = arr1 * 10
arr

array([ 10,  30,  90, 120, 180])

In [10]:
intarr1 = arr1.astype(np.int64)
intarr2 = arr2.astype(np.int64)
intarr3 = arr3.astype(np.int64)
intarr4 = arr4.astype(np.int64)
print('arr1', intarr1.dtype)
print('arr2', intarr2.dtype)
print('arr3', intarr3.dtype)
print('arr4', intarr4.dtype)


arr1 int64
arr2 int64
arr3 int64
arr4 int64


In [11]:
a1 = np.zeros((3,5))
a1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a2 = np.ones((2,8))
a2

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
import random
a3 = np.random.randint(0,15,(6,3))
print(a3)


[[13  2 11]
 [ 4  8 14]
 [ 9 11  4]
 [11  7 10]
 [10 13  4]
 [ 5 14 13]]


In [14]:
arr1[2:4] = arr1[2:4] ** 2

print(arr1)

[  1   3  81 144  18]


In [15]:
arr2[0,1] = arr2[0,1] **2
arr2[1,2] = arr2[1,2] **2
print(arr2)

[[ 1 25  2  0]
 [ 3  6 16  7]]


In [19]:
l = [['ML', 'OS', 'CCN'],['Os','AI','MP'],['CCN',"ML","AI"]]
arr = np.array(l)
(arr == 'ML') | (arr =='AI')

array([[ True, False, False],
       [False,  True, False],
       [False,  True,  True]])

In [ ]:
# transpose of matrix
print(arr2.T)
print(arr3.T)
print(arr4.T)

[[ 1  3]
 [25  6]
 [ 2 16]
 [ 0  7]]
[['7' '5' '3']
 ['6' '4' '2']]
[[11 34]
 [52 61]
 [20 43]
 [50 17]]


In [25]:
h= np.hstack((arr2, arr4))
print(h)

[[ 1 25  2  0 11 52 20 50]
 [ 3  6 16  7 34 61 43 17]]


In [27]:
v = np.vstack((arr2, arr4))
print(v)

[[ 1 25  2  0]
 [ 3  6 16  7]
 [11 52 20 50]
 [34 61 43 17]]


In [28]:
arr2.mean(0)
demeaned = arr2 - arr2.mean(0)
print(demeaned)

[[-1.   9.5 -7.  -3.5]
 [ 1.  -9.5  7.   3.5]]


In [29]:
arr2.reshape((4, 2))

array([[ 1, 25],
       [ 2,  0],
       [ 3,  6],
       [16,  7]])

In [34]:
l=[[60,70,50],[40,60,80],[70,55,65]]
scores = np.array(l)
np.amax(scores, axis =1)

array([70, 80, 70])

In [41]:
def gradepoint(marks):
    if marks  >=94:
        return (4)
    if 80<=marks <=84:
        return (3.7)
    if 75<=marks <=79:
        return (3.4)
    if 70<=marks <=74:
        return (3.0)
    if 67<=marks <=69:
        return (2.7)
    if 64<=marks <=66:
        return (2.4)
    if 60<=marks <=63:
        return (2.0)
    if 57<=marks <=59:
        return (1.7)
    if 54<=marks <=56:
        return (1.4)
    if 50 <= marks <=53:
        return (1.0)
    else:
        return 0.0

print(gradepoint(56))   



l=[[60,40,70],[70,60,55],[50,80,65]]
a=np.array(l)
sub1_ch = 2
sub2_ch = 3
sub3_ch = 4
sum=0
counter =1
for i in a:
    sum = ( gradepoint(i[0]) * sub1_ch) + (gradepoint(i[1]) * sub2_ch) +  (gradepoint(i[2]) * sub3_ch)
    chs= sub1_ch +sub2_ch + sub3_ch
    gpa=sum/chs
    print('student',counter,'CGPA :',gpa)
    counter +=1
    




1.4
student 1 CGPA : 1.7777777777777777
student 2 CGPA : 1.9555555555555557
student 3 CGPA : 2.5222222222222226


In [43]:
l = [['ML', 'OS', 'CCN'],['OS','AI','MP'],['CCN',"ML","AI"]]
arr= np.array(l)
np.unique(arr)

array(['AI', 'CCN', 'ML', 'MP', 'OS'], dtype='<U3')

In [47]:
a = np.random.randint(0,15,(4,4))
b = np.random.randint(0,15,(4,4))


print(a.dot(b))
print(np.linalg.inv(a))


[[163  22  74 124]
 [136 102 185 152]
 [168  68 163 212]
 [166  29  80 116]]
[[-2.6852459  -0.43934426  0.59672131  2.45901639]
 [ 1.09180328  0.28852459 -0.24262295 -1.03278689]
 [-0.05901639 -0.04262295  0.01311475  0.16393443]
 [ 1.04590164  0.1442623  -0.12131148 -1.01639344]]


In [ ]:
import h5py

A = [arr1, arr2, arr3]  # each arrX is a numpy array

with h5py.File('file.h5', 'w', libver='latest') as f:  # use 'latest' for performance

    for idx, arr in enumerate(A):
        dset = f.create_dataset(str(idx), shape=(240, 240), data=arr, chunks=(240, 240),
                                compression='gzip', compression_opts=9)

SyntaxError: invalid syntax (3166513845.py, line 1)